---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-controller-manager
  namespace: kube-system
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  labels:
    component: cloud-controller-manager
    tier: control-plane
  name: vsphere-cloud-controller-manager
  namespace: kube-system
spec:
  tolerations:
  - key: node.cloudprovider.kubernetes.io/uninitialized
    value: "true"
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  containers:
    - name: vsphere-cloud-controller-manager
      image: gcr.io/cloud-provider-vsphere/vsphere-cloud-controller-manager:latest
      args:
        - /bin/vsphere-cloud-controller-manager
        - --v=2
        - --cloud-config=/etc/cloud/vsphere.conf
        - --cloud-provider=vsphere
        - --use-service-account-credentials=true
        - --address=127.0.0.1
        - --leader-elect=false
        - --kubeconfig=/etc/srv/kubernetes/controller-manager.conf
      volumeMounts:
        - mountPath: /etc/srv/kubernetes/pki
          name: k8s-certs
          readOnly: true
        - mountPath: /etc/ssl/certs
          name: ca-certs
          readOnly: true
        - mountPath: /etc/srv/kubernetes/controller-manager.conf
          name: kubeconfig
          readOnly: true
        - mountPath: /etc/cloud
          name: cloud-config-volume
          readOnly: true
      resources:
        requests:
          cpu: 200m
  hostNetwork: true
  securityContext:
    runAsUser: 1001
  serviceAccountName: cloud-controller-manager
  volumes:
  - hostPath:
      path: /etc/srv/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/srv/kubernetes/controller-manager.conf
      type: FileOrCreate
    name: kubeconfig
  - name: cloud-config-volume
    configMap:
      name: cloud-config
